import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { AppSidebar } from "@/components/global/app-sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";

const publicSans = Public_Sans({
  variable: "--font-public-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${publicSans.className} antialiased`}>
        <div className="flex min-h-screen">
          <SidebarProvider>
            <AppSidebar />
            <main className="w-ful min-h-screen flex-1 py-2  px-6 ">
          
              <Navbar />
              {children}
            </main>
          </SidebarProvider>
        </div>
      </body>
    </html>
  );
}
